repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
      
  - repo: local
    hooks:
      - id: maven-pmd-spotbugs
        name: Run PMD and SpotBugs Security Checks
#       entry: mvnw.cmd clean compile pmd:check spotbugs:check
        entry: cmd.exe /c mvnw.cmd clean compile pmd:check spotbugs:check 
        language: system
        types: [java]
        pass_filenames: false
#        verbose: true
        description: Biên dịch code và quét bằng PMD & SpotBugs.