DROP DATABASE IF EXISTS `microshop_db`;
CREATE DATABASE IF NOT EXISTS `microshop_db` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `microshop_db`;

-- Nhóm bảng chung & người dùng
CREATE TABLE `HANGTHANHVIEN` (
    `MaHang` INT PRIMARY KEY AUTO_INCREMENT,
    `TenHang` VARCHAR(50) NOT NULL UNIQUE,
    `MucChiTieuToiThieu` DECIMAL(15, 0) NOT NULL,
    `DuongDanIcon` VARCHAR(255),
    `ChietKhau` DECIMAL(4, 2) DEFAULT 0.00
);

CREATE TABLE `NGUOIDUNG` (
    `MaNguoiDung` INT PRIMARY KEY AUTO_INCREMENT,
    `TenDangNhap` VARCHAR(50) NOT NULL UNIQUE,
    `MatKhau` VARCHAR(255) NOT NULL,
    `Email` VARCHAR(100) UNIQUE,
    `SoDienThoai` VARCHAR(15) UNIQUE,
    `VaiTro` VARCHAR(20) NOT NULL,
    `TongTienDaChi` DECIMAL(15, 0) DEFAULT 0,
    `MaHangThanhVien` INT DEFAULT 1,
    `ThoiGianTao` DATETIME DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (`MaHangThanhVien`) REFERENCES `HANGTHANHVIEN`(`MaHang`) ON DELETE SET NULL,
    CONSTRAINT CHECK_NGUOIDUNG_VaiTro CHECK (`VaiTro` IN ('USER', 'ADMIN'))
);

CREATE TABLE `DANHMUC` (
    `MaDanhMuc` INT PRIMARY KEY AUTO_INCREMENT,
    `TenDanhMuc` VARCHAR(100) NOT NULL UNIQUE
);

-- Nhóm bảng tài khoản gốc
CREATE TABLE `TAIKHOAN` (
    `MaTaiKhoan` INT PRIMARY KEY AUTO_INCREMENT,
    `MaDanhMuc` INT NOT NULL,
    `GiaGoc` DECIMAL(15, 0) NOT NULL,
    `GiaBan` DECIMAL(15, 0) NOT NULL,
    `TrangThai` VARCHAR(20) NOT NULL,
    `DiemNoiBat` TEXT,
    `LuotXem` INT DEFAULT 0,
    `ThoiGianDang` DATETIME DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (`MaDanhMuc`) REFERENCES `DANHMUC`(`MaDanhMuc`),
    CONSTRAINT CHECK_TAIKHOAN_TrangThai CHECK (`TrangThai` IN ('DANG_BAN', 'DA_BAN'))
);

CREATE TABLE `ANH_TAIKHOAN` (
    `MaAnh` INT PRIMARY KEY AUTO_INCREMENT,
    `MaTaiKhoan` INT NOT NULL,
    `DuongDanAnh` VARCHAR(255) NOT NULL,

    FOREIGN KEY (`MaTaiKhoan`) REFERENCES `TAIKHOAN`(`MaTaiKhoan`) ON DELETE CASCADE
);

-- Nhóm bảng tài khoản kế thừa
CREATE TABLE `TAIKHOAN_LIENQUAN` (
  `MaTaiKhoan` INT PRIMARY KEY,
  `TenDangNhap` VARCHAR(100) NOT NULL,
  `MatKhau` VARCHAR(255) NOT NULL, 
  `HangRank` VARCHAR(50),
  `SoTuong` INT,
  `SoTrangPhuc` INT,
  `BacNgoc` INT,
  `LoaiDangKy` VARCHAR(50),

  FOREIGN KEY (`MaTaiKhoan`) REFERENCES `TAIKHOAN`(`MaTaiKhoan`) ON DELETE CASCADE
);

CREATE TABLE `TAIKHOAN_FREEFIRE` (
  `MaTaiKhoan` INT PRIMARY KEY,
  `TenDangNhap` VARCHAR(100) NOT NULL, 
  `MatKhau` VARCHAR(255) NOT NULL, 
  `CoTheVoCuc` BOOLEAN,
  `SoSkinSung` INT,
  `HangRank` VARCHAR(50),
  `LoaiDangKy` VARCHAR(50),

  FOREIGN KEY (`MaTaiKhoan`) REFERENCES `TAIKHOAN`(`MaTaiKhoan`) ON DELETE CASCADE
);

CREATE TABLE `TAIKHOAN_RIOT` (
  `MaTaiKhoan` INT PRIMARY KEY,
  `TenDangNhap` VARCHAR(100) NOT NULL, 
  `MatKhau` VARCHAR(255) NOT NULL,
  `CapDoRiot` INT,
  `SoTuongLMHT` INT,
  `SoTrangPhucLMHT` INT,
  `SoDaSacLMHT` INT,
  `SoBieuCamLMHT` INT,
  `SoBieuTuongLMHT` INT,
  `HangRankLMHT` VARCHAR(50),
  `KhungRankLMHT` VARCHAR(50),
  `SoThuCungTFT` INT,
  `SoSanDauTFT` INT,
  `SoChuongLucTFT` INT,
  FOREIGN KEY (`MaTaiKhoan`) REFERENCES `TAIKHOAN`(`MaTaiKhoan`) ON DELETE CASCADE
);

-- Nhóm Bảng Dịch vụ Steam
CREATE TABLE `GAME_STEAM` (
  `MaGameSteam` INT PRIMARY KEY AUTO_INCREMENT,
  `TenGame` VARCHAR(255) NOT NULL,
  `MoTaGame` TEXT,
  `GiaGoc` DECIMAL(15, 0) NOT NULL, 
  `GiaBan` DECIMAL(15, 0) NOT NULL, 
  `LuotXem` INT DEFAULT 0,
  `ThoiGianDang` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `IdVideoTrailer` VARCHAR(255),
  `DuongDanAnh` VARCHAR(255)
);

CREATE TABLE `BAIVIET_GIOITHIEU` (
  `MaBaiViet` INT PRIMARY KEY AUTO_INCREMENT,
  `MaGameSteam` INT NOT NULL UNIQUE,
  `TieuDeBaiViet` VARCHAR(255),
  `NoiDung` LONGTEXT,
  `ThoiGianTao` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `ThoiGianCapNhatCuoi` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  FOREIGN KEY (`MaGameSteam`) REFERENCES `GAME_STEAM`(`MaGameSteam`) ON DELETE CASCADE
);

CREATE TABLE `TAIKHOAN_STEAM` (
  `MaTaiKhoanSteam` INT PRIMARY KEY AUTO_INCREMENT,
  `TenDangNhapSteam` VARCHAR(100) NOT NULL,
  `MatKhauSteam` VARCHAR(255) NOT NULL,
  `TongSoSlot` INT NOT NULL,
  `SoSlotDaBan` INT NOT NULL DEFAULT 0
);

CREATE TABLE `GAME_TAIKHOAN_STEAM` (
  `MaGameSteam` INT,
  `MaTaiKhoanSteam` INT,
  PRIMARY KEY (`MaGameSteam`, `MaTaiKhoanSteam`),

  FOREIGN KEY (`MaGameSteam`) REFERENCES `GAME_STEAM`(`MaGameSteam`) ON DELETE CASCADE,
  FOREIGN KEY (`MaTaiKhoanSteam`) REFERENCES `TAIKHOAN_STEAM`(`MaTaiKhoanSteam`) ON DELETE CASCADE
);

-- Nhóm Bảng Đơn hàng
CREATE TABLE `DONHANG` (
  `MaDonHang` INT PRIMARY KEY AUTO_INCREMENT,
  `MaNguoiDung` INT NOT NULL,
  `MaTaiKhoan` INT NOT NULL,
  `GiaMua` DECIMAL(15, 0) NOT NULL,
  `ThoiGianMua` DATETIME,
  `TrangThai` VARCHAR(20) NOT NULL,
  `ThoiGianTao` DATETIME DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (`MaNguoiDung`) REFERENCES `NGUOIDUNG`(`MaNguoiDung`),
  FOREIGN KEY (`MaTaiKhoan`) REFERENCES `TAIKHOAN`(`MaTaiKhoan`),
  CONSTRAINT CHECK_DONHANG_TrangThai CHECK (`TrangThai` IN ('CHO_THANH_TOAN', 'DA_HOAN_THANH', 'DA_HUY'))
);

CREATE TABLE `DONHANG_SLOT_STEAM` (
  `MaDonHangSlot` INT PRIMARY KEY AUTO_INCREMENT,
  `MaNguoiDung` INT NOT NULL,
  `MaGameSteam` INT NOT NULL,
  `MaTaiKhoanSteam` INT NOT NULL,
  `GiaMua` DECIMAL(15, 0) NOT NULL,
  `ThoiGianMua` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `TrangThai` VARCHAR(20) NOT NULL,
  `ThoiGianTao` DATETIME DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (`MaNguoiDung`) REFERENCES `NGUOIDUNG`(`MaNguoiDung`),
  FOREIGN KEY (`MaGameSteam`) REFERENCES `GAME_STEAM`(`MaGameSteam`),
  FOREIGN KEY (`MaTaiKhoanSteam`) REFERENCES `TAIKHOAN_STEAM`(`MaTaiKhoanSteam`),
  CONSTRAINT CHECK_DONHANG_SLOT_STEAM_TrangThai CHECK (`TrangThai` IN ('CHO_THANH_TOAN', 'DA_HOAN_THANH', 'DA_HUY'))
);